### ISSUE TITLE
emphasize specific authors in rendered bib items (e.g., student coauthors, self)

### ISSUE THREAD

**Issue by klaeufer** [gkthiruvathukal/cv#2]
This would be nice to have for an academic CV.

- In the main publication section, ability to emphasize oneself (e.g. bold)
- In the student research engagement section, ability to emphasize specific student authors (e.g. underline)

It might be a major mod to enable emphasizing specific authors in a rendered bib item.

Alternatively, if we had unique numbers for each subsection corresponding to a type of bib item, like j1, j2, ..., c1, c2, ..., then we could list the student authors by name and \cite the corresponding publications. This second approach might be more feasible. 

Yet another alternative might be simply to use unique numbers instead of restarting them for each subsection or a bib numbering style that generates unique numbers.

**Comment by gkthiruvathukal** [comment]
@klaeufer Using the time while i have my eye infection to work on lighter-weight items! 
I know this might sound crazy, but I'm thinking of having a new section, Student Mentoring, which would list their publications (or just \cite same). Thoughts?

**Comment by gkthiruvathukal** [comment]
I'm going to close this one for now. If we get some bandwidth, let's pair on this in the future.
